### ISSUE TITLE
BUILD ERROR on  ng build unity-angular

### ISSUE THREAD

**Issue by sahil13031997** [rgoddat/AngularUnity#5]
Hello,

I am trying to build unity library after getting in "AngularUnity-library" directory but facing following error:

BUILD ERROR
Could not resolve '../assets/Unity/UnityLoader.js' from dist\unity-angular\esm2015\lib\unity-angular.component.js
Error: Could not resolve '../assets/Unity/UnityLoader.js' from dist\unity-angular\esm2015\lib\unity-angular.component.js
    at error (C:\Users\sahil.singh02\Desktop\node_modules\rollup\dist\rollup.js:199:15)
    at C:\Users\sahil.singh02\Desktop\node_modules\rollup\dist\rollup.js:20784:25

Could not resolve '../assets/Unity/UnityLoader.js' from dist\unity-angular\esm2015\lib\unity-angular.component.js
Error: Could not resolve '../assets/Unity/UnityLoader.js' from dist\unity-angular\esm2015\lib\unity-angular.component.js
    at error (C:\Users\sahil.singh02\Desktop\node_modules\rollup\dist\rollup.js:199:15)
    at C:\Users\sahil.singh02\Desktop\node_modules\rollup\dist\rollup.js:20784:25

**Comment by levalleux-ludo** [comment]
@sahil13031997  I've got the same error.
I've copied projects\unity-angular\src\assets folder into dist\unity-angular\esm5 and dist\unity-angular\esm2015
Then, relaunch the build.
Btw, the assets folder still misses in the npm package after you've installed it in your project.
I've worked this around by copying the 'assets' folder in node_modules/unity-angular after installation. Best way would be to upgrade the npm package directive.

**Comment by sahil13031997** [comment]
It worked , Thanx Man

**Comment by sahil13031997** [comment]
Having Other issue:
On adding Own webGL build into  AngularUnity-library\src\assets\Unity\demo and changing  "appLocation" from "../assets/Unity/demo/demo.json"to "../assets/Unity/demo/OwnBuild.json" is throwing error  :

Uncaught SyntaxError: Unexpected token 'var'

core.js:1542 ERROR TypeError: UnityLoader[r] is not a function
    at UnityLoader.loadCode.Module (UnityLoader.js:4)
    at HTMLScriptElement.o.onload [as __zone_symbol__ON_PROPERTYload] (UnityLoader.js:4)
    at HTMLScriptElement.wrapFn (zone.js:1188)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3662)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1566)

anyone is facing this?
